alias:
  default: &default
    working_directory: /go/src/github.com/yahoojapan/athenz-authorizer
    docker:
      - image: circleci/golang:1.14
        environment:
          GOPATH: "/go"
          GO111MODULE: "on"
          REPO_NAME: "yahoojapan"
          IMAGE_NAME: "athenz-authorizer"
          GITHUB_API: "https://api.github.com/"
          DOCKER_USER: "kpango"
  setup_remote_docker: &setup_remote_docker
    version: 19.03.8

version: 2
jobs:
  test:
    <<: *default
    steps:
      - checkout
      - restore_cache:
          key: gosum-{{ .Branch }}-{{ checksum "go.sum" }}
      - run:
          name: preparation
          command: |
            go mod vendor
      - run:
          name: run tests
          command: |
            rm -rf example
            go test -v -race -covermode=atomic -coverprofile=coverage.out ./...
            go tool cover -html=coverage.out -o coverage.html
            bash <(curl -s https://codecov.io/bash)
      - store_artifacts:
          path: ./coverage.html
      - save_cache:
          key: gosum-{{ .Branch }}-{{ checksum "go.sum" }}
          paths:
            - ./vendor
  versioning:
    <<: *default
    steps:
      - checkout
      - run:
          name: check
          command: |
            mkdir -p "$HOME/.ssh/" && echo -e 'Host github.com\n\tStrictHostKeyChecking no\n' > ~/.ssh/config
            LAST_COMMIT="$(git log -1 --pretty=%B)"
            if [ -n "$CIRCLE_PULL_REQUEST" ]; then
              # If PR, use PR title instead of last commit msg
              PR_NUM="${CIRCLE_PULL_REQUEST##*/}"
              LAST_COMMIT="$(curl -s "${GITHUB_API}repos/${REPO_NAME}/${IMAGE_NAME}/pulls/${PR_NUM}" | jq -r .title)"
            fi
            printf 'LAST_COMMIT: %s\n' "${LAST_COMMIT}"
            touch ./.tag
            VERSION="$(git describe --abbrev=0 --tags)"
            # Diff to prevent pipeline re-runs.
            if [ -n "$(git diff "$VERSION")" ]; then
              VERSION=${VERSION:-'v0.0.0'}
              MAJOR="${VERSION%%.*}"; MAJOR="${MAJOR#v}"; VERSION="${VERSION#*.}"
              MINOR="${VERSION%%.*}"; VERSION="${VERSION#*.}"
              PATCH="${VERSION%%.*}"; VERSION="${VERSION#*.}"

              case "$LAST_COMMIT" in
              '[patch]'* | '[PATCH]'*)
                PATCH=$((PATCH+1))
                echo "v$MAJOR.$MINOR.$PATCH" > ./.tag
                ;;
              '[minor]'* | '[MINOR]'*)
                MINOR=$((MINOR+1))
                echo "v$MAJOR.$MINOR.0" > ./.tag
                ;;
              '[major]'* | '[MAJOR]'*)
                MAJOR=$((MAJOR+1))
                echo "v$MAJOR.0.0" > ./.tag
                ;;
              # Don't release (nightly images only)
              '[skip]'* | '[SKIP]'*)
                echo "Skip release..."
                ;;
              # Don't want to run CI.
              '[skip ci]'* | '[ci skip]'*)
                echo "Will skip CI..."
                ;;
              *)
                echo "Required prefixes: [major]/[minor]/[patch]/[skip]/[skip ci]"
                exit 1
                ;;
              esac
            else
              if [ -n "$VERSION" ]; then
                echo "No diff, skip tagging..."
              else
                echo "No diff, No tag. Tag it as \"v0.0.0\"."
                echo "v0.0.0" > ./.tag
              fi
            fi
      - run:
          name: echo version
          command: |
            TAG_FILE='./.tag' \
            && if [[ -s ${TAG_FILE} ]]; then echo "TAG: `cat "${TAG_FILE}"`"; else echo "TAG: (${TAG_FILE} is empty)"; fi
      - persist_to_workspace:
          root: .
          paths:
            - .
  push:
    <<: *default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: push tag and check PR body
          command: |
            mkdir -p $HOME/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            TAG=`cat ./.tag`
            if [ ! -z "$TAG" ]; then
              echo $TAG
              git tag $TAG
              git push https://${GITHUB_ACCESS_TOKEN}:x-oauth-basic@github.com/${REPO_NAME}/${IMAGE_NAME} --tags
            fi
      - persist_to_workspace:
          root: .
          paths:
            - .
  gh_release:
    <<: *default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: release
          command: |
            mkdir -p $HOME/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            TAG=`cat ./.tag`
            if [ ! -z "$TAG" ]; then
              echo "Create release: ${TAG}"
              curl -H "Authorization: token ${GITHUB_ACCESS_TOKEN}" \
                   -X POST \
                   -d "{\"tag_name\": \"${TAG}\"}" \
                   ${GITHUB_API}repos/${REPO_NAME}/${IMAGE_NAME}/releases
            fi

workflows:
  version: 2
  build:
    jobs:
      - test
      - versioning
      - push:
          filters:
            branches:
              only:
                - master
          requires:
            - test
            - versioning
      - gh_release:
          requires:
            - push
